export const DATA = [
    {
        id: 1,
        name: "Bitcoin",
        symbol: "BTC",
        price: 50000,
        change: 5,
        marketCap: 1000000,
        volume: 100000,
        circulatingSupply: 18000000,
        totalSupply: 21000000,
        svg: "https://cryptologos.cc/logos/bitcoin-btc-logo.png",
    },
    {
        id: 2,
        name: "Ethereum",
        symbol: "ETH",
        price: 4000,
        change: -2,
        marketCap: 500000,
        volume: 200000,
        circulatingSupply: 115000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/ethereum-eth-logo.png?v=014",
    },
    {
        id: 3,
        name: "Litecoin",
        symbol: "LTC",
        price: 200,
        change: 1,
        marketCap: 10000000,
        volume: 50000,
        circulatingSupply: 66000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/litecoin-ltc-logo.png?v=014",
    },
    {
        id: 4,
        name: "Ripple",
        symbol: "XRP",
        price: 1.5,
        change: -1,
        marketCap: 5000000,
        volume: 30000,
        circulatingSupply: 45000000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/xrp-xrp-logo.png?v=014",
    },
    {
        id: 5,
        name: "Cardano",
        symbol: "ADA",
        price: 2,
        change: 3,
        marketCap: 3000000,
        volume: 20000,
        circulatingSupply: 31000000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/cardano-ada-logo.png?v=014",
    },
    {
        id: 6,
        name: "Polkadot",
        symbol: "DOT",
        price: 30,
        change: 4,
        marketCap: 2000000,
        volume: 15000,
        circulatingSupply: 1000000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/polkadot-new-dot-logo.png?v=014",
    },
    {
        id: 7,
        name: "Chainlink",
        symbol: "LINK",
        price: 25,
        change: -3,
        marketCap: 1500000,
        volume: 12000,
        circulatingSupply: 400000000,
        totalSupply: null,
        svg: "https://cryptologos.cc/logos/chainlink-link-logo.png?v=014",
    },
];

export const CRYPTO_LIST = [
    {
        id: 1,
        name: "Bitcoin",
        price: 50000,
        change: -5,
        src: "./assets/images/image1.png",
    },
    {
        id: 2,
        name: "Ethereum",
        price: 4000,
        change: 3,
    },
    {
        id: 3,
        name: "Litecoin",
        price: 200,
        change: -1,
    },
];
